<a href="https://colab.research.google.com/github/jonrodrigues42/Bootcamp-Python-XPe/blob/master/XPE_Bootcamp_Python_M%C3%B3dulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Criação de Arrays

In [1]:
# importando as dependências
import numpy as np

In [ ]:
# help da função
np.array?

In [ ]:
# criando um array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("x: ", x)
print("shape: ", x.shape)

x:  [1 2 3]
shape:  (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criando um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1 2]
 [3 4]]
shape:  (2, 2)


In [ ]:
# array contendo apenas 0s e 1s
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim)
y = np.ones(dim)
print("x:\n", x)
print("x shape: ", x.shape)
print("\n\n")
print("y:\n", y)
print("y shape: ", y.shape)

x:
 [[0. 0.]
 [0. 0.]]
x shape:  (2, 2)



y:
 [[1. 1.]
 [1. 1.]]
y shape:  (2, 2)


In [ ]:
# criaçãode valroes dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(x_min, x_max, 6)
print("x: ", x)
print("shape: ", x.shape)

x:  [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [ ]:
# ciração da matriz identidade
x = np.eye(4)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [ ]:
# criação de valores aletórios
x = np.random.random(size=(2, 3))
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[0.61918198 0.459283   0.90162412]
 [0.54187572 0.75785055 0.73204858]]
shape:  (2, 3)


# Indexação de arrays

In [2]:
# os índices no Python vão de 0 a n-1
# onde n é o tamanho da dimensão
x = np.linspace(10, 100, 10)
print(f"x: {x}")
print(f"shape: {x.shape}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [5]:
# extração de elementos
print(f"x: {x}")
print(f"primeiro elemento: {x[0]}")
print(f"segundo elemento: {x[1]}")
print(f"último elemento: {x[9]}")
print(f"último (-1) elemento: {x[-1]}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
segundo elemento: 20.0
último elemento: 100.0
último (-1) elemento: 100.0


In [6]:
# slicing: extração de subarrays:
print(f"x: {x}")
print(f"dois primeiros elementos: {x[0:2]}") # 2 é exlusivo
print(f"dois primeiros elementos: {x[:2]}") # 2 é exlusivo, pode-se omitir 0 
print(f"dois últimos elementos: {x[-2:]}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primeiros elementos: [10. 20.]
dois últimos elementos: [ 90. 100.]


In [10]:
# slicing em arrys 2D (matrizes)
x = x.reshape(2, 5) # reshape de x para 2 linhas e 5 colunas
print(f"x:\n {x}")

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [13]:
# extração de elementos
print(f"x:\n {x}\n")
print(f"primeira linha, segunda coluna: {x[0, 1]}")
print(f"segunda linha, penúltima coluna: {x[1, -2]}")
print(f"última linha, última coluna: {x[-1, 4]}")
print(f"última linha, última coluna: {x[-1, -1]}")

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]

primeira linha, segunda coluna: 20.0
segunda linha, penúltima coluna: 90.0
última linha, última coluna: 100.0
última linha, última coluna: 100.0


In [18]:
# slicing: estração de subarrays
print(f"x:\n{x}\n")
print(f"primeira linha inteira: {x[0, :]}")
print(f"primeira linha, segunda à quarta colina: {x[0, 1:4]}")
print(f"última coluna inteira:\n {x[:, [-1]]}") # ao passar entre [-1] entre colchetes, mantêm os elementos no tipo coluna

x:
[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]

primeira linha inteira: [10. 20. 30. 40. 50.]
primeira linha, segunda à quarta colina: [20. 30. 40.]
última coluna inteira:
 [[ 50.]
 [100.]]


In [25]:
# atenção com compartilhamento de memória em subarrays!
x = np.array([1, 2, 3])
print(f"x antes: {x}")
y = x[:2]
y[0] = -100 # alteração do valor em y altera o valor de x
print(f"x depois: {x}") # um slicing é uma "shallow copy" do array original
print(f"y: {y}")

x antes: [1 2 3]
x depois: [-100    2    3]
y: [-100    2]


In [24]:
# atenção com compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print(f"x antes: {x}")
y = x[:2].copy()
y[0] = -100 # alteração do valor em y NÃO altera o valor de x
print(f"x depois: {x}")
print(f"y: {y}")

x antes: [1 2 3]
x depois: [1 2 3]
y: [-100    2]
