<a href="https://colab.research.google.com/github/jonrodrigues42/Bootcamp-Python-XPe/blob/master/XPE_Bootcamp_Python_M%C3%B3dulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importando as dependências
import numpy as np

In [ ]:
# help da função
np.array?

In [ ]:
# criando um array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("x: ", x)
print("shape: ", x.shape)

x:  [1 2 3]
shape:  (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criando um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1 2]
 [3 4]]
shape:  (2, 2)


In [ ]:
# array contendo apenas 0s e 1s
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim)
y = np.ones(dim)
print("x:\n", x)
print("x shape: ", x.shape)
print("\n\n")
print("y:\n", y)
print("y shape: ", y.shape)

x:
 [[0. 0.]
 [0. 0.]]
x shape:  (2, 2)



y:
 [[1. 1.]
 [1. 1.]]
y shape:  (2, 2)


In [ ]:
# criaçãode valroes dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(x_min, x_max, 6)
print("x: ", x)
print("shape: ", x.shape)

x:  [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [ ]:
# ciração da matriz identidade
x = np.eye(4)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [ ]:
# criação de valores aletórios
x = np.random.random(size=(2, 3))
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[0.61918198 0.459283   0.90162412]
 [0.54187572 0.75785055 0.73204858]]
shape:  (2, 3)
