<a href="https://colab.research.google.com/github/jonrodrigues42/Bootcamp-Python-XPe/blob/master/XPE_Bootcamp_Python_M%C3%B3dulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
# importando as dependências
import numpy as np

# Criação de arrays

In [ ]:
# help da função
np.array?

In [ ]:
# criando um array 1D: [1, 2, 3]
l = [1, 2, 3]
x = np.array(l)
print("x: ", x)
print("shape: ", x.shape)

x:  [1 2 3]
shape:  (3,)


In [ ]:
type(x)

numpy.ndarray

In [ ]:
# criando um array 2D: listas aninhadas
l = [[1, 2], [3, 4]]
x = np.array(l)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1 2]
 [3 4]]
shape:  (2, 2)


In [ ]:
# array contendo apenas 0s e 1s
dim = (2, 2) # (linhas, colunas)
x = np.zeros(dim)
y = np.ones(dim)
print("x:\n", x)
print("x shape: ", x.shape)
print("\n\n")
print("y:\n", y)
print("y shape: ", y.shape)

x:
 [[0. 0.]
 [0. 0.]]
x shape:  (2, 2)



y:
 [[1. 1.]
 [1. 1.]]
y shape:  (2, 2)


In [ ]:
# criaçãode valroes dentro de um intervalo
# valores uniformes entre 5 e 15
x_min, x_max = 5, 15
x = np.linspace(x_min, x_max, 6)
print("x: ", x)
print("shape: ", x.shape)

x:  [ 5.  7.  9. 11. 13. 15.]
shape:  (6,)


In [ ]:
# ciração da matriz identidade
x = np.eye(4)
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
shape:  (4, 4)


In [ ]:
# criação de valores aletórios
x = np.random.random(size=(2, 3))
print("x:\n", x)
print("shape: ", x.shape)

x:
 [[0.61918198 0.459283   0.90162412]
 [0.54187572 0.75785055 0.73204858]]
shape:  (2, 3)


# Indexação de arrays

In [ ]:
# os índices no Python vão de 0 a n-1
# onde n é o tamanho da dimensão
x = np.linspace(10, 100, 10)
print(f"x: {x}")
print(f"shape: {x.shape}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
shape: (10,)


In [ ]:
# extração de elementos
print(f"x: {x}")
print(f"primeiro elemento: {x[0]}")
print(f"segundo elemento: {x[1]}")
print(f"último elemento: {x[9]}")
print(f"último (-1) elemento: {x[-1]}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
primeiro elemento: 10.0
segundo elemento: 20.0
último elemento: 100.0
último (-1) elemento: 100.0


In [ ]:
# slicing: extração de subarrays:
print(f"x: {x}")
print(f"dois primeiros elementos: {x[0:2]}") # 2 é exlusivo
print(f"dois primeiros elementos: {x[:2]}") # 2 é exlusivo, pode-se omitir 0 
print(f"dois últimos elementos: {x[-2:]}")

x: [ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
dois primeiros elementos: [10. 20.]
dois primeiros elementos: [10. 20.]
dois últimos elementos: [ 90. 100.]


In [ ]:
# slicing em arrys 2D (matrizes)
x = x.reshape(2, 5) # reshape de x para 2 linhas e 5 colunas
print(f"x:\n {x}")

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]


In [ ]:
# extração de elementos
print(f"x:\n {x}\n")
print(f"primeira linha, segunda coluna: {x[0, 1]}")
print(f"segunda linha, penúltima coluna: {x[1, -2]}")
print(f"última linha, última coluna: {x[-1, 4]}")
print(f"última linha, última coluna: {x[-1, -1]}")

x:
 [[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]

primeira linha, segunda coluna: 20.0
segunda linha, penúltima coluna: 90.0
última linha, última coluna: 100.0
última linha, última coluna: 100.0


In [ ]:
# slicing: estração de subarrays
print(f"x:\n{x}\n")
print(f"primeira linha inteira: {x[0, :]}")
print(f"primeira linha, segunda à quarta colina: {x[0, 1:4]}")
print(f"última coluna inteira:\n {x[:, [-1]]}") # ao passar entre [-1] entre colchetes, mantêm os elementos no tipo coluna

x:
[[ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]]

primeira linha inteira: [10. 20. 30. 40. 50.]
primeira linha, segunda à quarta colina: [20. 30. 40.]
última coluna inteira:
 [[ 50.]
 [100.]]


In [ ]:
# atenção com compartilhamento de memória em subarrays!
x = np.array([1, 2, 3])
print(f"x antes: {x}")
y = x[:2]
y[0] = -100 # alteração do valor em y altera o valor de x
print(f"x depois: {x}") # um slicing é uma "shallow copy" do array original
print(f"y: {y}")

x antes: [1 2 3]
x depois: [-100    2    3]
y: [-100    2]


In [ ]:
# atenção com compartilhamento de memória em subarrays!!
x = np.array([1, 2, 3])
print(f"x antes: {x}")
y = x[:2].copy()
y[0] = -100 # alteração do valor em y NÃO altera o valor de x
print(f"x depois: {x}")
print(f"y: {y}")

x antes: [1 2 3]
x depois: [1 2 3]
y: [-100    2]


# Operações aritméticas

In [4]:
# criação de dois arrays x e y
x = np.ones((2, 2))
y = np.eye(2)
print(f"x: \n {x} \n")
print(f"y: \n {y} \n")

x: 
 [[1. 1.]
 [1. 1.]] 

y: 
 [[1. 0.]
 [0. 1.]] 



In [5]:
# soma
print(f"soma de dois arrays:\n {x + y}")
print(f"soma com float ou int:\n {x + 2}") # broadcasting

soma de dois arrays:
 [[2. 1.]
 [1. 2.]]
soma com float ou int:
 [[3. 3.]
 [3. 3.]]


In [6]:
# subtração
print(f"subtração de dois arrays:\n {x - y}")
print(f"subtração com float ou int:\n {x - 2}") # broadcasting

subtração de dois arrays:
 [[0. 1.]
 [1. 0.]]
subtração com float ou int:
 [[-1. -1.]
 [-1. -1.]]


In [9]:
# divisão
print(f"divisão de dois arrays:\n {x / y}")
print(f"divisão com float ou int:\n {x / 2}")

divisão de dois arrays:
 [[ 1. inf]
 [inf  1.]]
divisão com float ou int:
 [[0.5 0.5]
 [0.5 0.5]]


<ipython-input-9-6ab590008ebb>:2: RuntimeWarning: divide by zero encountered in true_divide
  print(f"divisão de dois arrays:\n {x / y}")


In [ ]:
# quando o broadcasting não funciona
# np.array([1, 2, 3]) + np.array([1, 2])

In [14]:
# soma, subtração e divisão
print(f"combinação de operações: \n {(x+y)/(x-2)}")

combinação de operações: 
 [[-2. -1.]
 [-1. -2.]]


# Funções aritméticas: multiplicação

In [16]:
# multiplicação elemento a elemento
print(f"x: \n {x}")
print(f"y: \n {y}")

x: 
 [[1. 1.]
 [1. 1.]]
y: 
 [[1. 0.]
 [0. 1.]]


In [17]:
# multiplicação
print(f"multiplicação de dois arrays:\n {x * y}")
print(f"multiplicação com float ou int:\n {x * 2}") # broadcasting

multiplicação de dois arrays:
 [[1. 0.]
 [0. 1.]]
multiplicação com float ou int:
 [[2. 2.]
 [2. 2.]]


In [18]:
# multiplicação matricial
print(f"multiplicação matricial (np.dot):\n {np.dot(x, y)}\n")
print(f"multiplicação matricial (@):\n {x @ y}\n")
print(f"multiplicação matricial (.dot):\n {x.dot(y)}")

multiplicação matricial (np.dot):
 [[1. 1.]
 [1. 1.]]

multiplicação matricial (@):
 [[1. 1.]
 [1. 1.]]

multiplicação matricial (.dot):
 [[1. 1.]
 [1. 1.]]


In [28]:
### teste
a = np.array([[3, 5], [2, 0]])
b = np.array([[4, 5, -2], [2, 1, 3]])
a @ b

array([[22, 20,  9],
       [ 8, 10, -4]])

**Exemplo:**  
Solução de um sistema de equações:  
```
  a + 2*b = 7  
3*a + 2*b = -11  
Solução analitica: (a, b) = (-1, 4)
```

Matricialmente, esse problema tem a seguinte forma:  

Ax = c, onde:
  - x = [a, b]
  - A = [[1, 2], [3, -2]]
  - c = [7, -11]  
Solução numérica: x = inv(A) @ c

In [29]:
# definição do problema
A = np.array([[1, 2], [3, -2]])
c = np.array([[7], [-11]])
print(f"A: \n {A}")
print(f"C: \n {c}")

A: 
 [[ 1  2]
 [ 3 -2]]
C: 
 [[  7]
 [-11]]


In [33]:
# solução
# np.linalg.inv traz a inversa da matriz
x = np.dot(np.linalg.inv(A), c)
# x = np.linalg.inv(A) @ c
print(f"(a, b): \n {x.ravel()}")

(a, b): 
 [-1.  4.]
